version: "3.6"
networks:
  frontend:
  backend:
services:
  db:
    image: postgres:12-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: db-password
    networks:
      - backend
  web:
    build: .
    # We want to avoid mapping Gemfile.lock, yarn.lock, etc but there is no way to exclude
    # files using `volumes`.
    volumes:
    - ./.rspec:/the-flying-dutchmen/.rspec
    - ./Procfile.docker.dev:/the-flying-dutchmen/Procfile.docker.dev
    - ./Rakefile:/the-flying-dutchmen/Rakefile
    - ./config.ru:/the-flying-dutchmen/config.ru
    - ./app:/the-flying-dutchmen/app
    - ./bin:/the-flying-dutchmen/bin
    - ./config:/the-flying-dutchmen/config
    - ./db:/the-flying-dutchmen/db
    - ./lib:/the-flying-dutchmen/lib
    - ./script:/the-flying-dutchmen/script
    - ./vendor:/the-flying-dutchmen/vendor
    - ./spec:/the-flying-dutchmen/spec
    working_dir: /the-flying-dutchmen
    environment:
      DB: postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: db-password
      BUNDLE_GEMFILE: /the-flying-dutchmen/Gemfile
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: script/docker-dev-start-web.sh
    networks:
      - backend
      - frontend
    ports:
      - "9292:9292"
      - "3035:3035"
    depends_on:
      - db
